[project]
name = "streamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Anmol Pandey", email = "153331506+anmol-pandey13@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
streamlit = "streamlit:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
