[project]
name = "skyguard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Anmol Pandey", email = "153331506+anmol-pandey13@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
    "streamlit>=1.63.0",
]

[project.scripts]
skyguard = "skyguard:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "scikit-learn",
]

[tool.uv.sources]
scikit-learn = { workspace = true }
